name: Vitest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  glados-verification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: observation-deck

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci
      - run: npm run test -- --run
